ittakesavillage/urls.py
from typing import Union, List

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import URLPattern, URLResolver, path, include

urlpatterns: List[Union['URLPattern', 'URLResolver']] = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

website/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('website.views.parent.urls', namespace='parent')),
    path('pro/', include('website.views.caregiver.urls', namespace='caregiver')),
]

website/views/caregiver/urls.py
from django.urls import path

from website.views.caregiver.home import HomeView
from website.views.caregiver.signup import SignUpView
from website.views.caregiver.membershipcard import membershipCardView

app_name = 'website'
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("signup", SignUpView.as_view(), name="signup"),
    path("membershipcard", membershipCardView.as_view(), name="membershipcard"),
]

website/views/parent/urls.py
from django.urls import path

from website.views.parent.appointment.create import AppointmentCreateView
from website.views.parent.home import HomeView
from website.views.parent.auth.login import LoginClientView
from website.views.parent.auth.logout import LogoutClientView
from website.views.parent.auth.signup import SignupView
from website.views.parent.caregiver.detail import CaregiverDetailView
from website.views.parent.caregiver.list import CaregiverListView
from website.views.parent.info.speciality import SpecialityInfoView

app_name = 'website'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginClientView.as_view(), name="login"),
    path('logout/', LogoutClientView.as_view(), name="logout"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('caregiver/', CaregiverListView.as_view(), name='caregiver_list'),
    path('caregiver/<int:pk>/', CaregiverDetailView.as_view(), name="caregiver_detail"),
    path('appointment/<int:pk>/', AppointmentCreateView.as_view(), name="appointment_create"),
    path('info/speciality/', SpecialityInfoView.as_view(), name="info_speciality"),
]

website/models/appointment.py
import datetime
from typing import Tuple

from django.db import models


class Appointment(models.Model):
    specialist = models.ForeignKey("website.Caregiver", on_delete=models.PROTECT)
    parent = models.ForeignKey("website.Parent", on_delete=models.PROTECT)

    start = models.DateTimeField()
    end = models.DateTimeField()

    booked_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.parent}   {self.start} - {self.end}"

website/models/caregiver.py
from decimal import Decimal
from typing import List

from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.db.models import Prefetch

from website.models.caregiver_consultation_slot import CaregiverConsultationSlot
from website.models.choices import Sex, Language


class CaregiverManager(models.Manager):
    def with_consultation_slots(self):
        return self.prefetch_related(
            Prefetch(
                "consultation_slots",
                queryset=CaregiverConsultationSlot.objects.order_by('week_day', 'start'),
                to_attr="available_consultation_slots",
            )
        )


class Caregiver(models.Model):
    first_name = models.CharField(max_length=240)
    last_name = models.CharField(max_length=240)
    email = models.EmailField(max_length=240)

    sex = models.CharField(max_length=1, choices=Sex.choices)
    address = models.OneToOneField(
        'website.CaregiverAddress',
        on_delete=models.PROTECT
    )

    profile_photo = models.ImageField(upload_to="caregivers/profile/")
    profile_video = models.URLField()

    languages = ArrayField(
        models.CharField(max_length=2, choices=Language.choices),
        size=3
    )
    description = models.TextField(max_length=640)

    physical = models.BooleanField(default=True)
    online = models.BooleanField(default=False)
    conditions = ArrayField(
        models.CharField(max_length=128),
        size=5,
    )

    ranking = models.FloatField()
    number_comments = models.PositiveIntegerField()

    objects = CaregiverManager()

    @property
    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.last_name} {self.first_name}"

    @property
    def min_rate(self) -> Decimal:
        specialities = self.specialities.all()
        return min((speciality.rate for speciality in specialities), default=Decimal(0))

    @property
    def max_rate(self) -> Decimal:
        specialities = self.specialities.all()
        return max((speciality.rate for speciality in specialities), default=Decimal(0))

    @property
    def languages_names(self) -> List[str]:
        return [value for label, value in Language.choices if label in self.languages]

website/models/caregiver_address.py
from django.db import models


class CaregiverAddress(models.Model):
    street = models.CharField(max_length=128)
    street_no = models.CharField(max_length=4)
    postal_code = models.IntegerField()
    city = models.CharField(max_length=128)
    country = models.CharField(max_length=64)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return f"{self.street} {self.street_no}, {self.postal_code} {self.city}"

website/models/caregiver_consultation_slot.py
from django.db import models

from website.models.choices import WeekDays


class CaregiverConsultationSlot(models.Model):
    specialist = models.ForeignKey("website.Caregiver", on_delete=models.PROTECT, related_name="consultation_slots")

    week_day = models.CharField(max_length=60, choices=WeekDays.choices)
    start = models.TimeField()
    end = models.TimeField()

    def __str__(self):
        return f"{self.specialist}  {self.week_day}: {self.start} -> {self.end}"

    def numeric_iso_week_day(self) -> int:
        return {
            WeekDays.MONDAY.value: 1,
            WeekDays.TUESDAY.value: 2,
            WeekDays.WEDNESDAY.value: 3,
            WeekDays.THURSDAY.value: 5,
            WeekDays.FRIDAY.value: 5,
            WeekDays.SATURDAY.value: 6,
            WeekDays.SUNDAY.value: 7,
        }[self.week_day]

website/models/caregiver_diploma.py
from django.db import models


class CaregiverDiploma(models.Model):
    caregiver = models.ForeignKey('website.Caregiver', on_delete=models.CASCADE, related_name='diplomas')
    name = models.CharField(max_length=240)
    year = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.caregiver} {self.name} - {self.year}"

website/models/caregiver_speciality.py
from django.db import models

from website.models.choices import Speciality


class CaregiverSpeciality(models.Model):
    caregiver = models.ForeignKey('website.Caregiver', on_delete=models.CASCADE, related_name='specialities')
    speciality = models.CharField(max_length=240, choices=Speciality.choices)

    rate = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"{self.caregiver} {self.speciality}"

website/models/choices.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Sex(models.TextChoices):
    MALE = 'M', _('Male')
    FEMALE = 'F', _('Female')
    OTHER = 'O', _('Other')


class Language(models.TextChoices):
    FRENCH = 'FR', _('French')
    ENGLISH = 'EN', _('English')
    DUTCH = 'NL', _('Dutch')
    PORTUGUESE = 'PT', _('Portuguese')


class Speciality(models.TextChoices):
    LACTATION = 'Certified Breastfeeding Specialist', _('Certified Breastfeeding Specialist'),
    HYPNO_BIRTHING = 'HypnoBirthing® Childbirth Educator', _('HypnoBirthing® Childbirth Educator')
    MIDWIFE = 'Midwife', _('Midwife')
    DOULA = 'Doula', _('Doula')
    LACTATION_BREASTFEEDING_CONSULTANT = 'Lactation/breastfeeding consultant', _('Lactation/breastfeeding consultant')
    BABYWEARING_SPECIALIST = 'Babywearing specialist', _('Babywearing specialist')
    SLEEP_SPECIALIST = 'Sleep specialist', _('Sleep specialist')
    PEDIATRICIAN = 'Pediatrician', _('Pediatrician')
    PERINATAL_PSYCHOLOGIST = 'Perinatal psychologist', _('Perinatal psychologist')
    PHYSICAL_THERAPIST = 'Physical therapist', _('Physical therapist')
    PRE_POST_NATAL_YOGA_TEACHER = 'Pre/post natal yoga teacher', _('Pre/post natal yoga teacher')
    PRE_POST_NATAL_MASSAGE = 'Pre/post natal massage', _('Pre/post natal massage')
    BABY_MASSAGE = 'Baby massage', _('Baby massage')
    PRE_POST_NATAL_PHYSICAL_THERAPIST = 'Pre/post natal physical therapist', _('Pre/post natal physical therapist')
    OSTEOPATH = 'Osteopath', _('Osteopath')
    PARENTING_COACH = 'Parenting coach', _('Parenting coach')
    PSYCHOMOTRICIAN = 'Psychomotrician', _('Psychomotrician')

    @classmethod
    def availability_choices(cls):
        return [
            (cls.LACTATION.name, cls.LACTATION.label),
            (cls.HYPNO_BIRTHING.name, cls.HYPNO_BIRTHING.label)
        ]


class City(models.TextChoices):
    BRUSSELS = 'Brussels', _('Brussels')
    ANTWERPEN = 'Antwerpen', _('Antwerpen')
    GHENT = 'Ghent', _('Ghent')


class WeekDays(models.TextChoices):
    MONDAY = "Monday", _("Monday")
    TUESDAY = "Tuesday", _("Tuesday")
    WEDNESDAY = "Wednesday", _("Wednesday")
    THURSDAY = "Thursday", _("Thursday")
    FRIDAY = "Friday", _("Friday")
    SATURDAY = "Saturday", _("Saturday")
    SUNDAY = "Sunday", _("Sunday")

website/models/parent.py
from django.contrib.auth.models import User
from django.db import models


class Parent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)

    @property
    def first_name(self) -> str:
        return self.user.first_name

    @property
    def last_name(self) -> str:
        return self.user.last_name

    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    @property
    def email(self) -> str:
        return self.user.email

website/templates/website/parent/blocks/appointment_calendar.html
<div class="table-responsive">
    <table class="table table-sm " style="table-layout: fixed">
        <thead>
            <tr>
                {% for day in days %}
                    <th>
                        <div class="vstack">
                            <div class="small-font"> {{ day|date:'D' }}</div>
                            <div class="small-font"> {{ day|date:'d' }}</div>
                        </div>
                    </th>
                {% endfor %}
            </tr>
        </thead>

        <tbody>
            {% for day_slots in slots %}
                {% if forloop.counter < limit %}
                    <tr>
                        {% for slot in day_slots %}
                            <td class="small-font">
                                {% if slot %}
                                    <button class="btn btn-outline-secondary btn-sm smaller-font">{{ slot.start|date:'H:i' }}</button>
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>

    </table>
</div>

website/templates/website/parent/blocks/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a href="{% url 'parent:home' %}" class="navbar-brand"><img class="logo" src ="/static/website/img/logoimg.png"><h4 style="padding: 5px 0px 0px 5px;">BearHug</h4></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.get_username }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'parent:logout' %}">{% trans 'Log out' %}</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'caregiver:home' %}">{% trans "I am a specialist"%} <i class="bi bi-box-arrow-in-right"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'parent:login' %}">{% trans 'Log in' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'parent:signup' %}">{% trans 'Sign up' %}</a>
                    </li>
                {% endif %}

                <li class="nav-item">
                    {% include "website/parent/blocks/select_language.html" %}
                </li>
            </ul>
        </div>
    </div>
</nav>

website/templates/website/parent/blocks/select_language.html
<form class="d-flex" role="search">
    <select class="form-select form-select-sm" id="select-lang">
        <option selected>EN</option>
        <option value="1">FR</option>
        <option value="2">NL</option>
    </select>
</form>