ittakesavillage/urls.py
from typing import Union, List

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import URLPattern, URLResolver, path, include

urlpatterns: List[Union['URLPattern', 'URLResolver']] = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

website/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('website.views.parent.urls', namespace='parent')),
    path('pro/', include('website.views.caregiver.urls', namespace='caregiver')),
]

website/views/caregiver/urls.py
from django.urls import path

from website.views.caregiver.home import HomeView
from website.views.caregiver.signup import SignUpView
from website.views.caregiver.membershipcard import membershipCardView

app_name = 'website'
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("signup", SignUpView.as_view(), name="signup"),
    path("membershipcard", membershipCardView.as_view(), name="membershipcard"),
]

website/views/parent/urls.py
from django.urls import path

from website.views.parent.appointment.create import AppointmentCreateView
from website.views.parent.home import HomeView
from website.views.parent.auth.login import LoginClientView
from website.views.parent.auth.logout import LogoutClientView
from website.views.parent.auth.signup import SignupView
from website.views.parent.caregiver.detail import CaregiverDetailView
from website.views.parent.caregiver.list import CaregiverListView
from website.views.parent.info.speciality import SpecialityInfoView

app_name = 'website'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginClientView.as_view(), name="login"),
    path('logout/', LogoutClientView.as_view(), name="logout"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('caregiver/', CaregiverListView.as_view(), name='caregiver_list'),
    path('caregiver/<int:pk>/', CaregiverDetailView.as_view(), name="caregiver_detail"),
    path('appointment/<int:pk>/', AppointmentCreateView.as_view(), name="appointment_create"),
    path('info/speciality/', SpecialityInfoView.as_view(), name="info_speciality"),
]

website/models/appointment.py
import datetime
from typing import Tuple

from django.db import models


class Appointment(models.Model):
    specialist = models.ForeignKey("website.Caregiver", on_delete=models.PROTECT)
    parent = models.ForeignKey("website.Parent", on_delete=models.PROTECT)

    start = models.DateTimeField()
    end = models.DateTimeField()

    booked_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.parent}   {self.start} - {self.end}"

website/models/caregiver.py
from decimal import Decimal
from typing import List

from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.db.models import Prefetch

from website.models.caregiver_consultation_slot import CaregiverConsultationSlot
from website.models.choices import Sex, Language


class CaregiverManager(models.Manager):
    def with_consultation_slots(self):
        return self.prefetch_related(
            Prefetch(
                "consultation_slots",
                queryset=CaregiverConsultationSlot.objects.order_by('week_day', 'start'),
                to_attr="available_consultation_slots",
            )
        )


class Caregiver(models.Model):
    first_name = models.CharField(max_length=240)
    last_name = models.CharField(max_length=240)
    email = models.EmailField(max_length=240)

    sex = models.CharField(max_length=1, choices=Sex.choices)
    address = models.OneToOneField(
        'website.CaregiverAddress',
        on_delete=models.PROTECT
    )

    profile_photo = models.ImageField(upload_to="caregivers/profile/")
    profile_video = models.URLField()

    languages = ArrayField(
        models.CharField(max_length=2, choices=Language.choices),
        size=3
    )
    description = models.TextField(max_length=640)

    physical = models.BooleanField(default=True)
    online = models.BooleanField(default=False)
    conditions = ArrayField(
        models.CharField(max_length=128),
        size=5,
    )

    ranking = models.FloatField()
    number_comments = models.PositiveIntegerField()

    objects = CaregiverManager()

    @property
    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.last_name} {self.first_name}"

    @property
    def min_rate(self) -> Decimal:
        specialities = self.specialities.all()
        return min((speciality.rate for speciality in specialities), default=Decimal(0))

    @property
    def max_rate(self) -> Decimal:
        specialities = self.specialities.all()
        return max((speciality.rate for speciality in specialities), default=Decimal(0))

    @property
    def languages_names(self) -> List[str]:
        return [value for label, value in Language.choices if label in self.languages]

website/models/caregiver_address.py
from django.db import models


class CaregiverAddress(models.Model):
    street = models.CharField(max_length=128)
    street_no = models.CharField(max_length=4)
    postal_code = models.IntegerField()
    city = models.CharField(max_length=128)
    country = models.CharField(max_length=64)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return f"{self.street} {self.street_no}, {self.postal_code} {self.city}"

website/models/caregiver_consultation_slot.py
from django.db import models

from website.models.choices import WeekDays


class CaregiverConsultationSlot(models.Model):
    specialist = models.ForeignKey("website.Caregiver", on_delete=models.PROTECT, related_name="consultation_slots")

    week_day = models.CharField(max_length=60, choices=WeekDays.choices)
    start = models.TimeField()
    end = models.TimeField()

    def __str__(self):
        return f"{self.specialist}  {self.week_day}: {self.start} -> {self.end}"

    def numeric_iso_week_day(self) -> int:
        return {
            WeekDays.MONDAY.value: 1,
            WeekDays.TUESDAY.value: 2,
            WeekDays.WEDNESDAY.value: 3,
            WeekDays.THURSDAY.value: 5,
            WeekDays.FRIDAY.value: 5,
            WeekDays.SATURDAY.value: 6,
            WeekDays.SUNDAY.value: 7,
        }[self.week_day]

website/models/caregiver_diploma.py
from django.db import models


class CaregiverDiploma(models.Model):
    caregiver = models.ForeignKey('website.Caregiver', on_delete=models.CASCADE, related_name='diplomas')
    name = models.CharField(max_length=240)
    year = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.caregiver} {self.name} - {self.year}"

website/models/caregiver_speciality.py
from django.db import models

from website.models.choices import Speciality


class CaregiverSpeciality(models.Model):
    caregiver = models.ForeignKey('website.Caregiver', on_delete=models.CASCADE, related_name='specialities')
    speciality = models.CharField(max_length=240, choices=Speciality.choices)

    rate = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"{self.caregiver} {self.speciality}"

website/models/choices.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Sex(models.TextChoices):
    MALE = 'M', _('Male')
    FEMALE = 'F', _('Female')
    OTHER = 'O', _('Other')


class Language(models.TextChoices):
    FRENCH = 'FR', _('French')
    ENGLISH = 'EN', _('English')
    DUTCH = 'NL', _('Dutch')
    PORTUGUESE = 'PT', _('Portuguese')


class Speciality(models.TextChoices):
    LACTATION = 'Certified Breastfeeding Specialist', _('Certified Breastfeeding Specialist'),
    HYPNO_BIRTHING = 'HypnoBirthing® Childbirth Educator', _('HypnoBirthing® Childbirth Educator')
    MIDWIFE = 'Midwife', _('Midwife')
    DOULA = 'Doula', _('Doula')
    LACTATION_BREASTFEEDING_CONSULTANT = 'Lactation/breastfeeding consultant', _('Lactation/breastfeeding consultant')
    BABYWEARING_SPECIALIST = 'Babywearing specialist', _('Babywearing specialist')
    SLEEP_SPECIALIST = 'Sleep specialist', _('Sleep specialist')
    PEDIATRICIAN = 'Pediatrician', _('Pediatrician')
    PERINATAL_PSYCHOLOGIST = 'Perinatal psychologist', _('Perinatal psychologist')
    PHYSICAL_THERAPIST = 'Physical therapist', _('Physical therapist')
    PRE_POST_NATAL_YOGA_TEACHER = 'Pre/post natal yoga teacher', _('Pre/post natal yoga teacher')
    PRE_POST_NATAL_MASSAGE = 'Pre/post natal massage', _('Pre/post natal massage')
    BABY_MASSAGE = 'Baby massage', _('Baby massage')
    PRE_POST_NATAL_PHYSICAL_THERAPIST = 'Pre/post natal physical therapist', _('Pre/post natal physical therapist')
    OSTEOPATH = 'Osteopath', _('Osteopath')
    PARENTING_COACH = 'Parenting coach', _('Parenting coach')
    PSYCHOMOTRICIAN = 'Psychomotrician', _('Psychomotrician')

    @classmethod
    def availability_choices(cls):
        return [
            (cls.LACTATION.name, cls.LACTATION.label),
            (cls.HYPNO_BIRTHING.name, cls.HYPNO_BIRTHING.label)
        ]


class City(models.TextChoices):
    BRUSSELS = 'Brussels', _('Brussels')
    ANTWERPEN = 'Antwerpen', _('Antwerpen')
    GHENT = 'Ghent', _('Ghent')


class WeekDays(models.TextChoices):
    MONDAY = "Monday", _("Monday")
    TUESDAY = "Tuesday", _("Tuesday")
    WEDNESDAY = "Wednesday", _("Wednesday")
    THURSDAY = "Thursday", _("Thursday")
    FRIDAY = "Friday", _("Friday")
    SATURDAY = "Saturday", _("Saturday")
    SUNDAY = "Sunday", _("Sunday")

website/models/parent.py
from django.contrib.auth.models import User
from django.db import models


class Parent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)

    @property
    def first_name(self) -> str:
        return self.user.first_name

    @property
    def last_name(self) -> str:
        return self.user.last_name

    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    @property
    def email(self) -> str:
        return self.user.email

website/templates/website/caregiver/home.html
{% extends 'website/caregiver/layout.html' %}

{% load static i18n %}


{% block content %}
    <div class="row mt-3 mx-3">
        <div class="col-md-5 my-auto">
            <h1>ARE YOU AN EARLY CHILDHOOD PROFESSIONAL?</h1>
            <h6>BE SEEN BY AN EVER-GROWING COMMUNITY OF PARENTS</h6>
            <p class="fw-lighter">Do you spend a lot of time on the phone handling bookings? And do you spend time and money on your marketing and customer acquisition?
                All the additional tasks that come with the profession can be daunting.                
                Let us free you from that burden so that you can go back to doing what you love: taking care of families!</p>
            <a class="btn btn-primary" href="{% url 'caregiver:signup' %}" role="button">{% trans 'Join us' %}</a>
        </div>

        <div class="col-md-7 text-end">
            <img src="{% static "website/img/family_consulting.jpg" %}" class="img-fluid" alt="">
        </div>
    </div>

    <br><br>
    <div class="row justify-content-around">
        <div class="col-md-3">
            
            <div class="card text-bg-light mb-3" style="max-width: 18rem;">
                <div class="card-header"> <h5 class="card-title">1 SIGN UP</h5> </div>
                <div class="card-body">
            
                  <p class="card-text">Sign up and choose the membership that best meets your needs. You can start with the free membership version and get a feel for the platform and get acquainted with our services. You can choose to stay present on the free membership for as long as you desire. When your needs grow you can then upgrade your membership. We grow with you and support you all throughout your career.</p>
                </div>
              </div>
        </div>
        <div class="col-md-3">
                        <div class="card text-bg-light mb-3" style="max-width: 18rem;">
                <div class="card-header"> <h5 class="card-title">2 CHOOSE THE SUPPORT YOU NEED</h5> </div>
                <div class="card-body">
            
                  <p class="card-text">Create a profile by completing the needed information in the profile creation step. This will allow parents to have a comprehensive view on your services, prices, consultation hours, location and more.</p>
                </div>
              </div>
        </div>
        <div class="col-md-3">
            <div class="card text-bg-light mb-3" style="max-width: 18rem;">
                <div class="card-header"> <h5 class="card-title">3 BOOK YOUR SESSION</h5> </div>
                <div class="card-body">
                 
                  <p class="card-text">Be seen by our ever-growing community of parents and enjoy bookings coming in. Get notifications when an appointment has been booked. No need anymore to work on your marketing, your referencing or to spend time and money on customer acquisition. We do it all for you. Benefit from easy-to-use interfaces and automated processes.</p>
                </div>
              </div>
    </div>
</div>
<br><br>
<div class="row mt-3 mx-3">
        <h3 class="text-center">YOUR ADVANTAGES</h3>
        <ul>
            <li>Optimize your online visibility</li>
            <li>Have an ever growing community of parents find you</li>
            <li>Get instant payments via our platform</li>
            <li>Decrease the number of no-shows</li>
            <li>Automate appointment confirmations and reminders</li>
            <li>Choose you own cancellation policy</li>
            <li>Have automated cancellations. No more need for calls or agenda updates</li>
            <li>Spend less time on the phone and let us take the urgent calls</li>
            <li>Use our digital calendar to have a 24/7 update on your schedule</li>
            <li>You can personalize your profile page and express your own professional style and personality</li>
            <li>Have previous patients leave reviews on your page to increase visibility and customer traction</li>
            <li>Many more..</li>
        </ul>
    </div>
        <a class="btn btn-primary" href="{% url 'caregiver:signup' %}" role="button">{% trans 'Learn More' %}</a>
    
{% endblock content %}

website/templates/website/caregiver/index.html
<!DOCTYPE html>
<html lang="en">

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
   
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
 
     <!-- Site Metas -->
    <title>Appfast - Responsive OnePage HTML5 Template</title>  
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <!-- Site CSS -->
    <link rel="stylesheet" href="style.css">    
    <!-- ALL VERSION CSS -->
    <link rel="stylesheet" href="css/versions.css">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="css/responsive.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/custom.css">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="app_version" data-spy="scroll" data-target="#navbarApp" data-offset="98">

    <!-- LOADER -->
    <!-- <div id="preloader">
        <img class="preloader" src="images/loaders/loader-app.gif" alt="">
    </div> end loader -->
    <!-- END LOADER -->
	
    <div id="pricing" class="section lb">
        <div class="container">
            <div class="section-title text-center">
                <h3>Ready to get started?</h3>
                <p class="lead">Get the red carpet treatment <strong>just $39 per month!</strong> It is estimated that 3.5 million established by personal blogs.<br> From each other, we share paid WordPress themes WP Service...</p>
            </div><!-- end title -->

            <div class="row">
                <div class="col-md-12">
                    <div class="tab-content">
                        <div class="tab-pane active fade show" id="tab1">
                            <div class="row text-center">
                                <div class="col-md-3">
                                    <div class="pricing-table pricing-table-highlighted">
                                        <div class="pricing-table-header grd1">
                                            <h2>Free Access</h2>
                                            <h3>$85/month</h3>
                                        </div>
                                        <div class="pricing-table-space"></div>
                                        <div class="pricing-table-features">
                                            <p> <strong>250</strong> Email Addresses</p>
                                            <p> <strong>125GB</strong> of Storage</p>
                                            <p><strong>140</strong> Databases</p>
                                            <p><strong>60</strong> Domains</p>
                                            <p><strong>24/7 Unlimited</strong> Support</p>
                                        </div>
                                        <div class="pricing-table-sign-up">
                                            <a href="#" class="btn btn-dark btn-radius btn-brd grd1 effect-1">Order Now</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="pricing-table pricing-table-highlighted">
                                        <div class="pricing-table-header grd1">
                                            <h2>Free Access</h2>
                                            <h3>$85/month</h3>
                                        </div>
                                        <div class="pricing-table-space"></div>
                                        <div class="pricing-table-features">
                                            <p> <strong>250</strong> Email Addresses</p>
                                            <p> <strong>125GB</strong> of Storage</p>
                                            <p><strong>140</strong> Databases</p>
                                            <p><strong>60</strong> Domains</p>
                                            <p><strong>24/7 Unlimited</strong> Support</p>
                                        </div>
                                        <div class="pricing-table-sign-up">
                                            <a href="#" class="btn btn-dark btn-radius btn-brd grd1 effect-1">Order Now</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="pricing-table pricing-table-highlighted">
                                        <div class="pricing-table-header grd1">
                                            <h2>1 Year Membership</h2>
                                            <h3>$59/year</h3>
                                        </div>
                                        <div class="pricing-table-space"></div>
                                        <div class="pricing-table-text">
                                            <p>This is a perfect choice for small businesses and startups.</p>
                                        </div>
                                        <div class="pricing-table-features">
                                            <p><strong>150</strong> Email Addresses</p>
                                            <p><strong>65GB</strong> of Storage</p>
                                            <p><strong>60</strong> Databases</p>
                                            <p><strong>30</strong> Domains</p>
                                            <p> <strong>24/7 Unlimited</strong> Support</p>
                                        </div>
                                        <div class="pricing-table-sign-up">
                                            <a href="#" class="btn btn-dark btn-radius btn-brd grd1 effect-1">Learn More</a>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="pricing-table pricing-table-highlighted">
                                        <div class="pricing-table-header grd1">
                                            <h2>Lifetime Update</h2>
                                            <h3>$85/one-time</h3>
                                        </div>
                                        <div class="pricing-table-space"></div>
                                        <div class="pricing-table-features">
                                            <p> <strong>250</strong> Email Addresses</p>
                                            <p><strong>125GB</strong> of Storage</p>
                                            <p><strong>140</strong> Databases</p>
                                            <p><strong>60</strong> Domains</p>
                                            <p><strong>24/7 Unlimited</strong> Support</p>
                                        </div>
                                        <div class="pricing-table-sign-up">
                                            <a href="#" class="btn btn-dark btn-radius btn-brd grd1 effect-1">Order Now</a>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- end row -->
                        </div><!-- end pane -->
                    </div><!-- end content -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->

 
    <!-- ALL JS FILES -->
    <script src="js/all.js"></script>
    <!-- ALL PLUGINS -->
    <script src="js/custom.js"></script>
	<script src="js/zenith.js"></script>
	<script>
		$('#default').zenith({
			layout: 'default' , 
			slideSpeed: 450, 
			autoplaySpeed: 2000
		});
	</script>

</body>
</html>

website/templates/website/caregiver/layout.html
{% load static i18n %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">

<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% block stylesheet %}
    <link rel="stylesheet" href="{% static 'website/bootstrap/css/bootstrap.css' %}" >
    <link rel="stylesheet" href="{% static 'website/bootstrap/icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'website/choicesjs/css/choices.css' %}">
    <link rel="stylesheet" href="{% static 'website/fullcalendar/main.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/specialist.css' %}">

    {% endblock %}

    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
    />
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.css"
rel="stylesheet"
/>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.js"
></script>
</head>

<body>

{% block navbar %}
    {% include "website/caregiver/blocks/navbar.html" %}
{% endblock %}

<div class="row">
    <div class="col-md-4 mx-auto">
        {% include "website/caregiver/blocks/messages.html" %}
    </div>
</div>

<div class="container-fluid">
    {% block content %}
    {% endblock content %}
</div>

<div class="container-fluid mb-3">
    <hr>
    <div class="row">
        <div class="offset-md-1 col-md-4 d-flex align-items-center">
            <span class="mb-3 mb-md-0 text-muted">© 2023 BearHug</span>
        </div>
        <div class="col-md-2">
            <small class="text-muted">
                <!-- <a class="text-reset" href="https://www.freepik.com/free-vector/family-consulting-doctor_5889554.htm#page=2&query=doctor&position=19&from_view=author">Image by pch.vector</a> on Freepik -->
            </small>
        </div> 
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">

            <li class="ms-3"><i class="bi bi-twitter"></i></li>
            <li class="ms-3"><i class="bi bi-instagram"></i></li>
            <li class="ms-3"><i class="bi bi-facebook"></i></li>
        </ul>
    </div>
</div>


{% block javascript %}
<script src="{% static 'website/bootstrap/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'website/choicesjs/js/choices.js' %}"></script>
<script src="{% static 'website/fullcalendar/main.js' %}"></script>
<script src="{% static 'website/js/calendar.js' %}"></script>
<script src="{% static 'website/js/form.js' %}"></script>
{% endblock javascript %}
</body>

</html>

website/templates/website/caregiver/signup.html
{% extends "website/caregiver/layout.html" %}

{% load i18n %}
{% load django_bootstrap5 %}

{% block content %}

    <div class="row mt-md-3">
        <div class="col-md-3 mx-auto">
            <h3>Join us</h3>
            <form method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form_errors form %}
                {% bootstrap_form form %}
                <!-- <button type="submit" class="btn btn-primary">
                    {% trans "Choose your membership" %}
                </button> -->
                <a class="btn btn-primary" href="{% url 'caregiver:membershipcard' %}" role="button">{% trans 'Choose your membership' %}</a>
            </form>
        </div>
    </div>

{% endblock content %}