ittakesavillage/urls.py
from typing import Union, List

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import URLPattern, URLResolver, path, include

urlpatterns: List[Union['URLPattern', 'URLResolver']] = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

website/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('website.views.parent.urls', namespace='parent')),
    path('pro/', include('website.views.caregiver.urls', namespace='caregiver')),
]

website/views/caregiver/urls.py
from django.urls import path

from website.views.caregiver.home import HomeView
from website.views.caregiver.signup import SignUpView
from website.views.caregiver.membershipcard import membershipCardView

app_name = 'website'
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("signup", SignUpView.as_view(), name="signup"),
    path("membershipcard", membershipCardView.as_view(), name="membershipcard"),
]

website/views/parent/urls.py
from django.urls import path

from website.views.parent.appointment.create import AppointmentCreateView
from website.views.parent.home import HomeView
from website.views.parent.auth.login import LoginClientView
from website.views.parent.auth.logout import LogoutClientView
from website.views.parent.auth.signup import SignupView
from website.views.parent.caregiver.detail import CaregiverDetailView
from website.views.parent.caregiver.list import CaregiverListView
from website.views.parent.info.speciality import SpecialityInfoView

app_name = 'website'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginClientView.as_view(), name="login"),
    path('logout/', LogoutClientView.as_view(), name="logout"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('caregiver/', CaregiverListView.as_view(), name='caregiver_list'),
    path('caregiver/<int:pk>/', CaregiverDetailView.as_view(), name="caregiver_detail"),
    path('appointment/<int:pk>/', AppointmentCreateView.as_view(), name="appointment_create"),
    path('info/speciality/', SpecialityInfoView.as_view(), name="info_speciality"),
]

website/models/appointment.py
import datetime
from typing import Tuple

from django.db import models


class Appointment(models.Model):
    specialist = models.ForeignKey("website.Caregiver", on_delete=models.PROTECT)
    parent = models.ForeignKey("website.Parent", on_delete=models.PROTECT)

    start = models.DateTimeField()
    end = models.DateTimeField()

    booked_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.parent}   {self.start} - {self.end}"

website/models/caregiver.py
from decimal import Decimal
from typing import List

from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.db.models import Prefetch

from website.models.caregiver_consultation_slot import CaregiverConsultationSlot
from website.models.choices import Sex, Language


class CaregiverManager(models.Manager):
    def with_consultation_slots(self):
        return self.prefetch_related(
            Prefetch(
                "consultation_slots",
                queryset=CaregiverConsultationSlot.objects.order_by('week_day', 'start'),
                to_attr="available_consultation_slots",
            )
        )


class Caregiver(models.Model):
    first_name = models.CharField(max_length=240)
    last_name = models.CharField(max_length=240)
    email = models.EmailField(max_length=240)

    sex = models.CharField(max_length=1, choices=Sex.choices)
    address = models.OneToOneField(
        'website.CaregiverAddress',
        on_delete=models.PROTECT
    )

    profile_photo = models.ImageField(upload_to="caregivers/profile/")
    profile_video = models.URLField()

    languages = ArrayField(
        models.CharField(max_length=2, choices=Language.choices),
        size=3
    )
    description = models.TextField(max_length=640)

    physical = models.BooleanField(default=True)
    online = models.BooleanField(default=False)
    conditions = ArrayField(
        models.CharField(max_length=128),
        size=5,
    )

    ranking = models.FloatField()
    number_comments = models.PositiveIntegerField()

    objects = CaregiverManager()

    @property
    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.last_name} {self.first_name}"

    @property
    def min_rate(self) -> Decimal:
        specialities = self.specialities.all()
        return min((speciality.rate for speciality in specialities), default=Decimal(0))

    @property
    def max_rate(self) -> Decimal:
        specialities = self.specialities.all()
        return max((speciality.rate for speciality in specialities), default=Decimal(0))

    @property
    def languages_names(self) -> List[str]:
        return [value for label, value in Language.choices if label in self.languages]

website/models/caregiver_address.py
from django.db import models


class CaregiverAddress(models.Model):
    street = models.CharField(max_length=128)
    street_no = models.CharField(max_length=4)
    postal_code = models.IntegerField()
    city = models.CharField(max_length=128)
    country = models.CharField(max_length=64)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return f"{self.street} {self.street_no}, {self.postal_code} {self.city}"

website/models/caregiver_consultation_slot.py
from django.db import models

from website.models.choices import WeekDays


class CaregiverConsultationSlot(models.Model):
    specialist = models.ForeignKey("website.Caregiver", on_delete=models.PROTECT, related_name="consultation_slots")

    week_day = models.CharField(max_length=60, choices=WeekDays.choices)
    start = models.TimeField()
    end = models.TimeField()

    def __str__(self):
        return f"{self.specialist}  {self.week_day}: {self.start} -> {self.end}"

    def numeric_iso_week_day(self) -> int:
        return {
            WeekDays.MONDAY.value: 1,
            WeekDays.TUESDAY.value: 2,
            WeekDays.WEDNESDAY.value: 3,
            WeekDays.THURSDAY.value: 5,
            WeekDays.FRIDAY.value: 5,
            WeekDays.SATURDAY.value: 6,
            WeekDays.SUNDAY.value: 7,
        }[self.week_day]

website/models/caregiver_diploma.py
from django.db import models


class CaregiverDiploma(models.Model):
    caregiver = models.ForeignKey('website.Caregiver', on_delete=models.CASCADE, related_name='diplomas')
    name = models.CharField(max_length=240)
    year = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.caregiver} {self.name} - {self.year}"

website/models/caregiver_speciality.py
from django.db import models

from website.models.choices import Speciality


class CaregiverSpeciality(models.Model):
    caregiver = models.ForeignKey('website.Caregiver', on_delete=models.CASCADE, related_name='specialities')
    speciality = models.CharField(max_length=240, choices=Speciality.choices)

    rate = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"{self.caregiver} {self.speciality}"

website/models/choices.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Sex(models.TextChoices):
    MALE = 'M', _('Male')
    FEMALE = 'F', _('Female')
    OTHER = 'O', _('Other')


class Language(models.TextChoices):
    FRENCH = 'FR', _('French')
    ENGLISH = 'EN', _('English')
    DUTCH = 'NL', _('Dutch')
    PORTUGUESE = 'PT', _('Portuguese')


class Speciality(models.TextChoices):
    LACTATION = 'Certified Breastfeeding Specialist', _('Certified Breastfeeding Specialist'),
    HYPNO_BIRTHING = 'HypnoBirthing® Childbirth Educator', _('HypnoBirthing® Childbirth Educator')
    MIDWIFE = 'Midwife', _('Midwife')
    DOULA = 'Doula', _('Doula')
    LACTATION_BREASTFEEDING_CONSULTANT = 'Lactation/breastfeeding consultant', _('Lactation/breastfeeding consultant')
    BABYWEARING_SPECIALIST = 'Babywearing specialist', _('Babywearing specialist')
    SLEEP_SPECIALIST = 'Sleep specialist', _('Sleep specialist')
    PEDIATRICIAN = 'Pediatrician', _('Pediatrician')
    PERINATAL_PSYCHOLOGIST = 'Perinatal psychologist', _('Perinatal psychologist')
    PHYSICAL_THERAPIST = 'Physical therapist', _('Physical therapist')
    PRE_POST_NATAL_YOGA_TEACHER = 'Pre/post natal yoga teacher', _('Pre/post natal yoga teacher')
    PRE_POST_NATAL_MASSAGE = 'Pre/post natal massage', _('Pre/post natal massage')
    BABY_MASSAGE = 'Baby massage', _('Baby massage')
    PRE_POST_NATAL_PHYSICAL_THERAPIST = 'Pre/post natal physical therapist', _('Pre/post natal physical therapist')
    OSTEOPATH = 'Osteopath', _('Osteopath')
    PARENTING_COACH = 'Parenting coach', _('Parenting coach')
    PSYCHOMOTRICIAN = 'Psychomotrician', _('Psychomotrician')

    @classmethod
    def availability_choices(cls):
        return [
            (cls.LACTATION.name, cls.LACTATION.label),
            (cls.HYPNO_BIRTHING.name, cls.HYPNO_BIRTHING.label)
        ]


class City(models.TextChoices):
    BRUSSELS = 'Brussels', _('Brussels')
    ANTWERPEN = 'Antwerpen', _('Antwerpen')
    GHENT = 'Ghent', _('Ghent')


class WeekDays(models.TextChoices):
    MONDAY = "Monday", _("Monday")
    TUESDAY = "Tuesday", _("Tuesday")
    WEDNESDAY = "Wednesday", _("Wednesday")
    THURSDAY = "Thursday", _("Thursday")
    FRIDAY = "Friday", _("Friday")
    SATURDAY = "Saturday", _("Saturday")
    SUNDAY = "Sunday", _("Sunday")

website/models/parent.py
from django.contrib.auth.models import User
from django.db import models


class Parent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)

    @property
    def first_name(self) -> str:
        return self.user.first_name

    @property
    def last_name(self) -> str:
        return self.user.last_name

    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    @property
    def email(self) -> str:
        return self.user.email

website/templates/website/parent/caregiver/blocks/availability.html
{% load i18n %}
{% load django_bootstrap5 %}
{% load parent_extras %}
<div class="card">
    <div class="card-body">
        <h4 class="card-title"><i class="bi bi-currency-euro"></i> {{ caregiver.min_rate|floatformat }} - {{ caregiver.max_rate|floatformat }}</h4>
        <hr class="border border-dark opacity-75">
        <form action="{% url 'parent:appointment_create' caregiver.pk %}" method="post">
           <!-- {% csrf_token %}

            {% bootstrap_field form.speciality layout='floating' %}
            {% bootstrap_field form.first_appointment %}
            {% bootstrap_field form.second_appointment %}-->
              <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
                <label class="form-check-label" for="flexRadioDefault1">
                  First Appointment
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2">
                <label class="form-check-label" for="flexRadioDefault2">
                  Second Appointment
                </label>
              </div>

            <div class="row">
                <div class="col-md-8 mx-auto">

                </div>
            </div>
            {% show_appointment_calendar caregiver.consultation_slots 100 %}
            <hr class="border border-primary opacity-75">
            <button type="submit" class="btn btn-primary w-100">{% trans "Make an appointment" %}</button>
        </form>
    </div>
</div>

website/templates/website/parent/caregiver/blocks/caregiver_detail.html
{% load i18n static %}
<div class="row mb-md-3">
    <div class="col-md-3">
        <img src="{{ caregiver.profile_photo.url }}" alt="" class="img-fluid" max-width: "100%" height: "auto">
    </div>
    <div class="col-md-9">
        <h4>
            {{ caregiver.full_name }}
            <small class="fs-6 fw-light ms-3">{% include 'website/parent/caregiver/blocks/rank.html' with ranking=caregiver.ranking number_comments=caregiver.number_comments %}</small>
        </h4>

        {% for speciality in caregiver.specialities.all %}
            <span class="badge rounded-pill text-bg-info">{{speciality.speciality}}</span>
        {% endfor %}

        <p><i class="bi bi-geo-alt-fill"></i> {{ caregiver.address }}</p>
    </div>
</div>


<!--<div class="ratio ratio-16x9">
    <iframe
            src="{{ caregiver.profile_video}}"
            title="YouTube video player"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen>
    </iframe>
</div>-->

<div class="card mt-3">
    <div class="card-header">
        <i class="bi bi-person-square"></i> Profile
    </div>
    <div class="card-body">
        <p class="card-text">
            {{ caregiver.description }}
        </p>

        <dl class="row">
            <dt class="col-sm-4"><i class="bi bi-globe"></i> Languages</dt>
            <dd class="col-sm-8">
                {% for language in caregiver.languages_names %}
                    {{ language }}{% if not forloop.last %},{% endif %}
                {% endfor %}
            </dd>
        </dl>

        <hr>

        <dl class="row">
            <dt class="col-sm-4"><i class="bi bi-mortarboard"></i> {% trans 'Diploma' %}</dt>
            <dd class="col-sm-8">
                <table class="table table-sm">
                    <tbody>
                        {% for diploma in caregiver.diplomas.all %}
                        <tr>
                            <td>{{ diploma.name }}</td>
                            <td>{{ diploma.year }}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td>-</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </dd>
        </dl>

    </div>
</div>

<div class="card mt-3">
    <div class="card-header">
        <i class="bi bi-currency-euro"></i> Prices
    </div>
    <div class="card-body">
        <table class="table ">
            <tbody>
            {% for speciality in caregiver.specialities.all %}
                <tr>
                    <td>{{ speciality.speciality }}</td>
                    <td>{{ speciality.rate|floatformat }} <i class="bi bi-currency-euro"></i></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>


<div class="card mt-3">
    <div class="card-header">
    <i class="bi bi-info-circle"></i>  Conditions
    </div>
    <div class="card-body">
        <ul class="list-group list-group-flush">
            {% for condition in caregiver.conditions %}
            <li class="list-group-item">{{ condition }}</li>
            {% endfor %}
        </ul>

    </div>
</div>

website/templates/website/parent/caregiver/blocks/caregiver_list_item.html
{% load static %}
{% load parent_extras %}

<div class="row  me-1">
    <div class="card mb-3" id="card-{{ item_number }}">
        <div class="row">
            <div class="col-2 align-self-center">
                <a href="{% url 'parent:caregiver_detail' caregiver.pk %}">
                    <img style="height: 120px;width: 150px; border-radius: 13px;" src="{{ caregiver.profile_photo.url }}" class="img-fluid" alt="">
                </a>
            </div>
            <div v class="col-6">
                <div class="card-body">
                    <h5 class="card-title">
                        <a class="text-reset" href="{% url 'parent:caregiver_detail' caregiver.pk %}">{{ caregiver.full_name }}</a>
                        <small class="fs-6 fw-light ms-3">{% include 'website/parent/caregiver/blocks/rank.html' with ranking=4.5 number_comments=125 %}</small>
                    </h5>
                    <h6 class="card-subtitle fw-normal mb-2">{{ caregiver.speciality }}</h6>
                    {% for speciality in caregiver.specialities.all %}
                    <h6 class="card-subtitle fw-normal mb-2" data-bs-toggle="tooltip" data-bs-title="The {{ speciality.speciality }} is ...">
                        {{ speciality.speciality }}
                    </h6>
                    {% endfor %}
                    <p class="card-text text-muted"><small>{{ caregiver.address }}</small></p>
                    <div
                            class="map-marker"
                            data-latitude="{{ caregiver.address.latitude }}"
                            data-longitude="{{ caregiver.address.longitude }}"
                            data-event="click"
                            data-param="#card-{{ item_number }}"
                    ></div>
                </div>
            </div>

            <div class="col-4 my-auto">

                    {% show_appointment_calendar caregiver.consultation_slots %}

            </div>
        </div>
    </div>


</div>

website/templates/website/parent/caregiver/blocks/caregiver_list_search.html
{% load django_bootstrap5 %}
<form method="get">
    <div class="input-group mb-3">
        <div class="form-floating">
            <select name="speciality" class="form-select" id="id_speciality">
                {% for option_speciality in form.speciality|dictsort:'data.label' %}
                    <option value="{{ option_speciality }}"></option>
                {% endfor %}
            </select>

            <label class="form-label" for="id_speciality">Speciality</label>
        </div>
        <span style="height: 58px;" class="input-group-text">
            <a class="link-dark" href="{% url 'parent:info_speciality' %}" target="_blank"><i class="bi bi-question-circle-fill"></i></a>
        </span>
    </div>

    {% bootstrap_field form.speciality layout='floating' %}
    {% bootstrap_field form.location layout='floating' %}
    {% bootstrap_field form.language show_label=false %}
    {% bootstrap_field form.appointments show_label=false %}
    {% bootstrap_field form.sex layout='floating' %}

    <button type="submit" class="btn btn-primary">
        <i class="bi bi-search"></i>
    </button>
</form>

website/templates/website/parent/caregiver/blocks/rank.html
{{ ranking }}
{% if ranking < 1 %}
    <i class="bi bi-star"></i>
    <i class="bi bi-star"></i>
    <i class="bi bi-star"></i>
    <i class="bi bi-star"></i>
    <i class="bi bi-star"></i>
{% elif ranking < 2 %}
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star"></i>
    <i class="bi bi-star"></i>
    <i class="bi bi-star"></i>
    <i class="bi bi-star"></i>
{% elif ranking < 3 %}
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star"></i>
    <i class="bi bi-star"></i>
    <i class="bi bi-star"></i>
{% elif ranking < 4 %}
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star"></i>
    <i class="bi bi-star"></i>
{% elif ranking < 4.5 %}
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star"></i>
{% else %}
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star-fill"></i>
    <i class="bi bi-star-half"></i>
{% endif %}
({{ number_comments }})

website/templates/website/parent/caregiver/blocks/slot.html
{% if slot %}
<input type="radio" class="btn-check" id="btn-radio-{{ slot.timestamp }}" autocomplete="off" name="slot" value="{{ slot.start.isoformat }}" required>
<label class="btn btn-outline-dark bnt-sm smaller-font " for="btn-radio-{{ slot.timestamp }}">{{ slot.start|date:'H:i' }}</label>
    {% else %}
    -
{% endif %}